-- =============================================================================
-- V19: user_addresses -- customer self-service saved shipping addresses.
--
-- Convenience feature only: business documents (orders, invoices, returns,
-- shipments, refunds) always read the immutable orders.* shipping-address
-- snapshot (see V18), never this table, once an order exists. There is no
-- foreign key from orders to this table.
--
-- Column widths match the DTO's @Size caps exactly (see UserAddressDto),
-- same discipline as V18, so an over-limit value can never pass bean
-- validation and then fail at INSERT.
--
-- country is unrestricted here on purpose (unlike checkout's ShippingAddress,
-- which is currently DE-only via AllowedShippingCountries) -- a customer may
-- save an address for a country not yet shippable; checkout rejects using it
-- with a clear error rather than the address book blocking them from saving
-- it in the first place.
-- =============================================================================

CREATE TABLE IF NOT EXISTS user_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    street varchar(255) NOT NULL,
    house_number varchar(16) NOT NULL,
    address_line2 varchar(255),
    postal_code varchar(16) NOT NULL,
    city varchar(128) NOT NULL,
    country varchar(2) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_addresses_user_id ON user_addresses(user_id);
