-- =============================================================================
-- V20: oauth_accounts -- links an external OAuth identity (currently only Google)
-- to an Enunas user, and makes users.password optional for OAuth-only accounts.
--
-- UNIQUE(provider, provider_user_id): a single external identity must never be
-- linkable to two different Enunas users.
-- UNIQUE(user_id, provider): each user gets at most one connection per provider
-- (only Google exists today; still correct if a second provider is added later,
-- since the constraint is per-provider, not global).
--
-- users.password DROP NOT NULL: safe, non-destructive -- every existing row
-- already has a non-null password, this only loosens the constraint for new
-- Google-only signups going forward.
-- =============================================================================

CREATE TABLE IF NOT EXISTS oauth_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    provider varchar(50) NOT NULL,
    provider_user_id varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uq_oauth_accounts_provider_identity UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_oauth_accounts_user_provider UNIQUE (user_id, provider)
);

ALTER TABLE users ALTER COLUMN password DROP NOT NULL;
