-- Order.status/shippingCarrier/trackingNumber/shippedAt/problemDescription used to be single,
-- order-wide values — on a multi-brand order, one brand's confirmShipment/reportShippingProblem
-- silently overwrote them for every other brand on the same order. This introduces per-(order,
-- brand) shipment tracking (order_shipments, mirroring the existing per-brand "returns" table) and
-- a new PARTIALLY_SHIPPED order status representing "some but not all brands have shipped".
--
-- orders.shipping_carrier/tracking_number/shipped_at/problem_description/problem_reported_at/
-- problem_reported_by are intentionally NOT dropped: existing orders carry real historical values
-- there (unlike customers.total_orders/total_spent, which V26 could safely drop because nothing
-- had ever written to them). They're simply no longer written going forward — see Order.java.

create table order_shipments (
    id                   bigint generated by default as identity primary key,
    order_id             bigint not null references orders(id),
    brand_partner_id     bigint not null references brand_partners(id),
    status               varchar(30) not null default 'AWAITING_SHIPMENT'
                             check (status in ('AWAITING_SHIPMENT', 'SHIPPED', 'PROBLEM')),
    carrier              varchar(100),
    tracking_number      varchar(100),
    shipped_at           timestamp(6),
    problem_description  varchar(1000),
    problem_reported_at  timestamp(6),
    problem_reported_by  varchar(255),
    created_at           timestamp(6) not null,
    updated_at           timestamp(6) not null,
    constraint uk_order_shipment_brand unique (order_id, brand_partner_id)
);

create index idx_order_shipments_order_id on order_shipments(order_id);

alter table orders add column has_shipping_problem boolean not null default false;

alter table orders drop constraint orders_status_check;
alter table orders add constraint orders_status_check check (status in (
    'PENDING', 'PAID', 'PARTIALLY_SHIPPED', 'SHIPPED', 'DELIVERED',
    'SHIPPING_PROBLEM', 'AWAITING_ADMIN', 'MANUAL_REVIEW',
    'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURN_RECEIVED', 'REFUNDED', 'CANCELLED'
));

-- ============================================================================
-- Backfill review list — NOT an automatic backfill. Deliberately writes ZERO rows to
-- order_shipments for historical orders. Reasoning: an order reaching SHIPPED (or beyond) under
-- the OLD single-track model only proves SOME brand shipped — the bug this migration fixes made
-- one brand's confirmShipment silently mark the WHOLE order (every brand) as SHIPPED, so we cannot
-- tell, from order.status alone, whether every brand on a historical multi-brand order genuinely
-- shipped or was swept along by the bug. Guessing "all shipped" would write false data into a
-- financial/logistics record; guessing nothing leaves brand-scoped views showing AWAITING_SHIPMENT
-- under an order whose status already says SHIPPED — confusing, but not a fabrication.
--
-- This table is a one-time, plain SQL artifact for manual review — no JPA entity, no repository,
-- never read by application code. is_ambiguous = false rows (single-brand orders) are safe to bulk-
-- approve; is_ambiguous = true rows (multi-brand) need a human judgment call per order, per the
-- reasoning above. Once reviewed, whoever processes this writes the resulting order_shipments rows
-- directly (or via a follow-up migration) — this migration does not do that itself.
-- ============================================================================

create table shipment_backfill_review (
    id                        bigint generated by default as identity primary key,
    order_id                  bigint not null references orders(id),
    order_number              varchar(255) not null,
    order_status              varchar(30) not null,
    brand_partner_id          bigint not null references brand_partners(id),
    brand_name                varchar(255) not null,
    is_ambiguous              boolean not null,
    legacy_shipping_carrier   varchar(255),
    legacy_tracking_number    varchar(255),
    legacy_shipped_at         timestamp(6),
    reviewed                  boolean not null default false,
    reviewed_at               timestamp(6),
    reviewed_note             varchar(500)
);

insert into shipment_backfill_review (
    order_id, order_number, order_status, brand_partner_id, brand_name,
    is_ambiguous, legacy_shipping_carrier, legacy_tracking_number, legacy_shipped_at
)
select
    o.id, o.order_number, o.status, ob.brand_partner_id, ob.brand_name,
    (dbc.distinct_brand_count > 1),
    o.shipping_carrier, o.tracking_number, o.shipped_at
from orders o
join (
    select distinct oi.order_id, p.brand_id as brand_partner_id, bp.brand_name
    from order_items oi
    join product_variants v on v.id = oi.variant_id
    join products p on p.id = v.product_id
    join brand_partners bp on bp.id = p.brand_id
) ob on ob.order_id = o.id
join (
    -- Separate GROUP BY (not a DISTINCT window aggregate — Postgres doesn't support
    -- COUNT(DISTINCT x) OVER (...)) for how many distinct brands are on each order.
    select oi.order_id, count(distinct p.brand_id) as distinct_brand_count
    from order_items oi
    join product_variants v on v.id = oi.variant_id
    join products p on p.id = v.product_id
    group by oi.order_id
) dbc on dbc.order_id = o.id
where o.status in ('SHIPPED', 'DELIVERED', 'RETURN_REQUESTED', 'RETURN_APPROVED', 'RETURN_RECEIVED', 'REFUNDED');
