-- =============================================================================
-- V3: Discount codes
--
-- Adds the two-type discount-code system:
--   1. discount_codes — the redeemable codes (ADMIN = platform-absorbed,
--      BRAND = 50/50 split, brand-scoped).
--   2. orders — order-level discount snapshot (immutable; keeps history correct
--      even if a code is later edited or deactivated).
--   3. order_items — per-item discount split, the seam the ledger reads from.
--
-- Idempotent and safe on databases that already have the schema (Hibernate ran
-- with ddl-auto previously, or a re-run): CREATE TABLE / ADD COLUMN use IF NOT
-- EXISTS and the FK is wrapped in a DO block that swallows duplicate_object.
-- Column names/types match what Hibernate's `validate` expects from the entities.
-- =============================================================================

-- 1. discount_codes ----------------------------------------------------------

create table if not exists discount_codes (
    id                 bigint generated by default as identity,
    code               varchar(255) not null unique,
    type               varchar(255) not null check ((type in ('ADMIN','BRAND'))),
    percent            numeric(5,4) not null,
    brand_id           bigint,
    valid_from         timestamp(6),
    valid_until        timestamp(6),
    max_uses           integer,
    used_count         integer not null,
    active             boolean not null,
    created_by_user_id bigint,
    created_at         timestamp(6),
    updated_at         timestamp(6),
    primary key (id)
);

create index if not exists idx_discount_codes_brand on discount_codes (brand_id);

DO $$ BEGIN
    ALTER TABLE discount_codes ADD CONSTRAINT fk_discount_codes_brand
        FOREIGN KEY (brand_id) REFERENCES brand_partners;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. orders — order-level discount snapshot ----------------------------------

alter table orders add column if not exists discount_code             varchar(255);
alter table orders add column if not exists discount_type             varchar(255);
alter table orders add column if not exists discount_percent          numeric(5,4);
alter table orders add column if not exists discount_amount           numeric(10,2);
alter table orders add column if not exists platform_discount_amount  numeric(10,2);
alter table orders add column if not exists brand_discount_amount     numeric(10,2);

DO $$ BEGIN
    ALTER TABLE orders ADD CONSTRAINT orders_discount_type_check
        CHECK (discount_type IS NULL OR discount_type IN ('ADMIN','BRAND'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 3. order_items — per-item discount split -----------------------------------

alter table order_items add column if not exists item_discount_amount    numeric(10,2);
alter table order_items add column if not exists platform_discount_share numeric(10,2);
alter table order_items add column if not exists brand_discount_share    numeric(10,2);
